# Site settings
title: Open San Diego Website
email: info@opensandiego.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.opensandiego.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/

collections:
  pages:
    output: true
    permalink: /:path
  projects:
    output: true
    permalink: /projects/:path
  notes:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
